### ISSUE TITLE
does packetdup work in current version?

### ISSUE THREAD

**Issue by fishxz** [AndreyNazarov/q2pro#101]
hey,
ive got told by ppl to enable packetdup, so i checked it and didnt found any command to enable it, so i looked with my tiny knowledge in the source code and seen, that the part with the "packetdup" command ist commented out, so i can not easy check if its work or not.

now my question is: why is this part commented out and does packetdup works and is it just the command which is disabled to check it?

**Comment by jar3817** [comment]
Looks like you have to define USE_PACKETDUP in the Makefile in order to get that functionality. I changed line 120 and 121 to this and it worked:

CFLAGS_s += $(BUILD_DEFS) $(VER_DEFS) $(PATH_DEFS) -DUSE_SERVER=1 -DUSE_PACKETDUP=1
CFLAGS_c += $(BUILD_DEFS) $(VER_DEFS) $(PATH_DEFS) -DUSE_SERVER=1 -DUSE_CLIENT=1 -DUSE_PACKETDUP=1

**Comment by fishxz** [comment]
i gonna try this. thank you
